# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2203b1345f36537615b15602da50a9d1"
name = "Taggstar Social Proof Plugin"
application_url = "https://childhood-stockings-comes-consumption.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customer_events,read_orders,read_pixels,write_pixels,write_products"

[auth]
redirect_urls = [
  "https://childhood-stockings-comes-consumption.trycloudflare.com/api/auth"
]
